version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - TZ=GMT

  stats-db:
    image: postgres:14-alpine
    container_name: posgres-ewm-stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stats-db
      - TZ=GMT

  ewm-service:
    build: main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
        - "8080:8080"
    depends_on:
        - ewm-db
        - stats-server
    environment:
        - stats-server.url=http://stats-server:9090
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=admin
        - TZ=GMT

  ewm-db:
     image: postgres:14-alpine
     container_name: postgres-ewm-db
     ports:
      - "6540:5432"
     volumes:
      - /var/lib/postgresql/data/
     environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ewm-db
      - TZ=GMT
